### ISSUE TITLE
This part is not Pythonic

### ISSUE THREAD

**Issue by nicolas-chan-42** [howardchanth/COMP3353_A3#1]
https://github.com/howardchanth/COMP3353_A3/blob/e1b97f483f92c492dde1f6b593ea83a927c56ca6/Task7/Q7.py#L8-L12

The code is functional but not written in a Pythonic way.
- You can iterate on strings directly in Python. Thus, you don't need `range(len(...))`.
- Line continuation using `\` is not a good practice. Implicit continuation with brackets is preferred in most style guides.
- Putting operators at the end of the line is not a good practice. Putting it at the beginning of the new line is preferred.

A more Pythonic way of writing would be something like
```Python
for i, j in zip(s1, s2): 
    if ((i.upper() == "A" and j.upper() == "G")
            or (i.upper() == "C" and j.upper() == "T")
            or (i.upper() == "G" and j.upper() == "A")
            or (i.upper() == "T" and j.upper() == "C")): 
```

It would be even better if you do the `upper()` method to both `i` and `j` before the if-statement.

**Comment by nicolas-chan-42** [comment]
Since you should have already submitted this assignment, @howardchanth you can simply close this issue/suggestion thread.
I just want to point out the possibility to you.

**Comment by howardchanth** [comment]
Thanks XD
